# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.Address do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"street",
    :"house_number",
    :"po_box",
    :"postal_code",
    :"city",
    :"country",
    :"extra",
    :"mailbox_name",
    :"province"
  ]

  @type t :: %__MODULE__{
    :"street" => String.t | nil,
    :"house_number" => String.t | nil,
    :"po_box" => String.t | nil,
    :"postal_code" => String.t | nil,
    :"city" => String.t | nil,
    :"country" => String.t | nil,
    :"extra" => String.t | nil,
    :"mailbox_name" => String.t | nil,
    :"province" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.Address do
  def decode(value, _options) do
    value
  end
end
