# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.Amount do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"value",
    :"currency"
  ]

  @type t :: %__MODULE__{
    :"value" => String.t | nil,
    :"currency" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.Amount do
  def decode(value, _options) do
    value
  end
end

