# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.Attachment do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"description",
    :"content_type"
  ]

  @type t :: %__MODULE__{
    :"description" => String.t | nil,
    :"content_type" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.Attachment do
  def decode(value, _options) do
    value
  end
end

