# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.AvatarRead do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"uuid",
    :"image"
  ]

  @type t :: %__MODULE__{
    :"uuid" => String.t | nil,
    :"image" => [Image] | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.AvatarRead do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"image", :list, Bunq.Model.Image, options)
  end
end

