# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.BankSwitchServiceNetherlandsIncoming do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"alias",
    :"counterparty_alias",
    :"status",
    :"sub_status",
    :"time_start_actual",
    :"user_alias",
    :"time_start_desired",
    :"time_end",
    :"attachment"
  ]

  @type t :: %__MODULE__{
    :"alias" => LabelMonetaryAccount | nil,
    :"counterparty_alias" => LabelMonetaryAccount | nil,
    :"status" => String.t | nil,
    :"sub_status" => String.t | nil,
    :"time_start_actual" => String.t | nil,
    :"user_alias" => LabelUser | nil,
    :"time_start_desired" => String.t | nil,
    :"time_end" => String.t | nil,
    :"attachment" => Attachment | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.BankSwitchServiceNetherlandsIncoming do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"alias", :struct, Bunq.Model.LabelMonetaryAccount, options)
    |> deserialize(:"counterparty_alias", :struct, Bunq.Model.LabelMonetaryAccount, options)
    |> deserialize(:"user_alias", :struct, Bunq.Model.LabelUser, options)
    |> deserialize(:"attachment", :struct, Bunq.Model.Attachment, options)
  end
end

