# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.BillingContractSubscriptionListing do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"created",
    :"updated",
    :"contract_date_start",
    :"contract_date_end",
    :"contract_version",
    :"subscription_type",
    :"subscription_type_downgrade",
    :"status",
    :"sub_status"
  ]

  @type t :: %__MODULE__{
    :"id" => integer() | nil,
    :"created" => String.t | nil,
    :"updated" => String.t | nil,
    :"contract_date_start" => String.t | nil,
    :"contract_date_end" => String.t | nil,
    :"contract_version" => integer() | nil,
    :"subscription_type" => String.t | nil,
    :"subscription_type_downgrade" => String.t | nil,
    :"status" => String.t | nil,
    :"sub_status" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.BillingContractSubscriptionListing do
  def decode(value, _options) do
    value
  end
end

