# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.BudgetRestriction do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"amount",
    :"frequency"
  ]

  @type t :: %__MODULE__{
    :"amount" => Amount | nil,
    :"frequency" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.BudgetRestriction do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"amount", :struct, Bunq.Model.Amount, options)
  end
end

