# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.BunqMeTab do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"bunqme_tab_entry",
    :"status"
  ]

  @type t :: %__MODULE__{
    :"bunqme_tab_entry" => BunqMeTabEntry,
    :"status" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.BunqMeTab do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"bunqme_tab_entry", :struct, Bunq.Model.BunqMeTabEntry, options)
  end
end

