# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.BunqMeMerchantAvailable do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"merchant_type",
    :"available"
  ]

  @type t :: %__MODULE__{
    :"merchant_type" => String.t | nil,
    :"available" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.BunqMeMerchantAvailable do
  def decode(value, _options) do
    value
  end
end

