# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.BunqMeTabRead do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"created",
    :"updated",
    :"time_expiry",
    :"monetary_account_id",
    :"status",
    :"bunqme_tab_share_url",
    :"bunqme_tab_entry",
    :"result_inquiries"
  ]

  @type t :: %__MODULE__{
    :"id" => integer() | nil,
    :"created" => String.t | nil,
    :"updated" => String.t | nil,
    :"time_expiry" => String.t | nil,
    :"monetary_account_id" => integer() | nil,
    :"status" => String.t | nil,
    :"bunqme_tab_share_url" => String.t | nil,
    :"bunqme_tab_entry" => BunqMeTabEntry | nil,
    :"result_inquiries" => [BunqMeTabResultInquiry] | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.BunqMeTabRead do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"bunqme_tab_entry", :struct, Bunq.Model.BunqMeTabEntry, options)
    |> deserialize(:"result_inquiries", :list, Bunq.Model.BunqMeTabResultInquiry, options)
  end
end

