# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.BunqMeFundraiserProfileUserListing do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"monetary_account_id",
    :"color",
    :"alias",
    :"description",
    :"attachment",
    :"pointer",
    :"redirect_url",
    :"status"
  ]

  @type t :: %__MODULE__{
    :"monetary_account_id" => integer() | nil,
    :"color" => String.t | nil,
    :"alias" => LabelMonetaryAccount | nil,
    :"description" => String.t | nil,
    :"attachment" => Map | nil,
    :"pointer" => Pointer | nil,
    :"redirect_url" => String.t | nil,
    :"status" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.BunqMeFundraiserProfileUserListing do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"alias", :struct, Bunq.Model.LabelMonetaryAccount, options)
    |> deserialize(:"attachment", :struct, Bunq.Model.Map, options)
    |> deserialize(:"pointer", :struct, Bunq.Model.Pointer, options)
  end
end

