# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.CardBatchEntry do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"status",
    :"card_limit",
    :"card_limit_atm",
    :"country_permission",
    :"monetary_account_id_fallback"
  ]

  @type t :: %__MODULE__{
    :"id" => integer(),
    :"status" => String.t | nil,
    :"card_limit" => Amount | nil,
    :"card_limit_atm" => Amount | nil,
    :"country_permission" => [CardCountryPermission] | nil,
    :"monetary_account_id_fallback" => integer() | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.CardBatchEntry do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"card_limit", :struct, Bunq.Model.Amount, options)
    |> deserialize(:"card_limit_atm", :struct, Bunq.Model.Amount, options)
    |> deserialize(:"country_permission", :list, Bunq.Model.CardCountryPermission, options)
  end
end

