# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.CardPinAssignment do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"type",
    :"pin_code",
    :"monetary_account_id"
  ]

  @type t :: %__MODULE__{
    :"type" => String.t | nil,
    :"pin_code" => String.t | nil,
    :"monetary_account_id" => integer() | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.CardPinAssignment do
  def decode(value, _options) do
    value
  end
end

