# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.CardBatchCreate do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"updated_card_ids"
  ]

  @type t :: %__MODULE__{
    :"updated_card_ids" => [BunqId] | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.CardBatchCreate do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"updated_card_ids", :list, Bunq.Model.BunqId, options)
  end
end

