# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.CardDebit do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"second_line",
    :"name_on_card",
    :"alias",
    :"type",
    :"pin_code_assignment",
    :"monetary_account_id_fallback"
  ]

  @type t :: %__MODULE__{
    :"second_line" => String.t,
    :"name_on_card" => String.t,
    :"alias" => Pointer | nil,
    :"type" => String.t | nil,
    :"pin_code_assignment" => [CardPinAssignment] | nil,
    :"monetary_account_id_fallback" => integer() | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.CardDebit do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"alias", :struct, Bunq.Model.Pointer, options)
    |> deserialize(:"pin_code_assignment", :list, Bunq.Model.CardPinAssignment, options)
  end
end

