# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.CardMagStripePermission do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"expiry_time"
  ]

  @type t :: %__MODULE__{
    :"expiry_time" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.CardMagStripePermission do
  def decode(value, _options) do
    value
  end
end

