# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.CardGeneratedCvc2Listing do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"created",
    :"updated",
    :"type",
    :"cvc2",
    :"status",
    :"expiry_time"
  ]

  @type t :: %__MODULE__{
    :"id" => integer() | nil,
    :"created" => String.t | nil,
    :"updated" => String.t | nil,
    :"type" => String.t | nil,
    :"cvc2" => String.t | nil,
    :"status" => String.t | nil,
    :"expiry_time" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.CardGeneratedCvc2Listing do
  def decode(value, _options) do
    value
  end
end

