# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.CardCountryPermission do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"country",
    :"expiry_time",
    :"id"
  ]

  @type t :: %__MODULE__{
    :"country" => String.t | nil,
    :"expiry_time" => String.t | nil,
    :"id" => integer() | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.CardCountryPermission do
  def decode(value, _options) do
    value
  end
end

