# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.CardReplace do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name_on_card",
    :"pin_code",
    :"second_line"
  ]

  @type t :: %__MODULE__{
    :"name_on_card" => String.t | nil,
    :"pin_code" => String.t | nil,
    :"second_line" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.CardReplace do
  def decode(value, _options) do
    value
  end
end

