# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.CardBatch do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"cards"
  ]

  @type t :: %__MODULE__{
    :"cards" => [CardBatchEntry]
  }
end

defimpl Poison.Decoder, for: Bunq.Model.CardBatch do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"cards", :list, Bunq.Model.CardBatchEntry, options)
  end
end

