# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.CashRegisterQrCodeListing do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"created",
    :"updated",
    :"status",
    :"cash_register",
    :"tab_object"
  ]

  @type t :: %__MODULE__{
    :"id" => integer() | nil,
    :"created" => String.t | nil,
    :"updated" => String.t | nil,
    :"status" => String.t | nil,
    :"cash_register" => CashRegister | nil,
    :"tab_object" => Tab | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.CashRegisterQrCodeListing do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"cash_register", :struct, Bunq.Model.CashRegister, options)
    |> deserialize(:"tab_object", :struct, Bunq.Model.Tab, options)
  end
end

