# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.CashRegister do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"status",
    :"avatar_uuid",
    :"location",
    :"notification_filters",
    :"tab_text_waiting_screen",
    :"id",
    :"created",
    :"updated",
    :"avatar"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t | nil,
    :"status" => String.t | nil,
    :"avatar_uuid" => String.t,
    :"location" => Geolocation | nil,
    :"notification_filters" => [NotificationFilter] | nil,
    :"tab_text_waiting_screen" => [TabTextWaitingScreen] | nil,
    :"id" => integer() | nil,
    :"created" => String.t | nil,
    :"updated" => String.t | nil,
    :"avatar" => Avatar | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.CashRegister do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"location", :struct, Bunq.Model.Geolocation, options)
    |> deserialize(:"notification_filters", :list, Bunq.Model.NotificationFilter, options)
    |> deserialize(:"tab_text_waiting_screen", :list, Bunq.Model.TabTextWaitingScreen, options)
    |> deserialize(:"avatar", :struct, Bunq.Model.Avatar, options)
  end
end

