# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.CertificatePinned do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"certificate_chain"
  ]

  @type t :: %__MODULE__{
    :"certificate_chain" => [Certificate]
  }
end

defimpl Poison.Decoder, for: Bunq.Model.CertificatePinned do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"certificate_chain", :list, Bunq.Model.Certificate, options)
  end
end

