# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.ConfirmationOfFunds do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"pointer_iban",
    :"amount"
  ]

  @type t :: %__MODULE__{
    :"pointer_iban" => Pointer,
    :"amount" => Amount
  }
end

defimpl Poison.Decoder, for: Bunq.Model.ConfirmationOfFunds do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"pointer_iban", :struct, Bunq.Model.Pointer, options)
    |> deserialize(:"amount", :struct, Bunq.Model.Amount, options)
  end
end

