# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.CustomerStatementExport do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"statement_format",
    :"date_start",
    :"date_end",
    :"regional_format"
  ]

  @type t :: %__MODULE__{
    :"statement_format" => String.t,
    :"date_start" => String.t,
    :"date_end" => String.t,
    :"regional_format" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.CustomerStatementExport do
  def decode(value, _options) do
    value
  end
end

