# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.DeviceServer do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"description",
    :"secret",
    :"permitted_ips"
  ]

  @type t :: %__MODULE__{
    :"description" => String.t,
    :"secret" => String.t,
    :"permitted_ips" => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.DeviceServer do
  def decode(value, _options) do
    value
  end
end

