# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.DeviceServerListing do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"created",
    :"updated",
    :"description",
    :"ip",
    :"status"
  ]

  @type t :: %__MODULE__{
    :"id" => integer() | nil,
    :"created" => String.t | nil,
    :"updated" => String.t | nil,
    :"description" => String.t | nil,
    :"ip" => String.t | nil,
    :"status" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.DeviceServerListing do
  def decode(value, _options) do
    value
  end
end

