# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.DeviceRead do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"DeviceServer"
  ]

  @type t :: %__MODULE__{
    :"DeviceServer" => DeviceServer | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.DeviceRead do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"DeviceServer", :struct, Bunq.Model.DeviceServer, options)
  end
end

