# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.DraftShareInviteEntry do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"share_detail",
    :"start_date",
    :"end_date"
  ]

  @type t :: %__MODULE__{
    :"share_detail" => ShareDetail | nil,
    :"start_date" => String.t | nil,
    :"end_date" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.DraftShareInviteEntry do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"share_detail", :struct, Bunq.Model.ShareDetail, options)
  end
end

