# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.DraftShareInviteBankRead do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"user_alias_created",
    :"status",
    :"expiration",
    :"share_invite_bank_response_id",
    :"draft_share_url",
    :"draft_share_settings",
    :"id"
  ]

  @type t :: %__MODULE__{
    :"user_alias_created" => LabelUser | nil,
    :"status" => String.t | nil,
    :"expiration" => String.t | nil,
    :"share_invite_bank_response_id" => integer() | nil,
    :"draft_share_url" => String.t | nil,
    :"draft_share_settings" => DraftShareInviteEntry | nil,
    :"id" => integer() | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.DraftShareInviteBankRead do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"user_alias_created", :struct, Bunq.Model.LabelUser, options)
    |> deserialize(:"draft_share_settings", :struct, Bunq.Model.DraftShareInviteEntry, options)
  end
end

