# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.DraftPaymentResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"status",
    :"user_alias_created"
  ]

  @type t :: %__MODULE__{
    :"status" => String.t | nil,
    :"user_alias_created" => LabelUser | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.DraftPaymentResponse do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"user_alias_created", :struct, Bunq.Model.LabelUser, options)
  end
end

