# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.DraftPaymentListing do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"monetary_account_id",
    :"user_alias_created",
    :"responses",
    :"status",
    :"type",
    :"entries",
    :"object",
    :"request_reference_split_the_bill",
    :"schedule"
  ]

  @type t :: %__MODULE__{
    :"id" => integer() | nil,
    :"monetary_account_id" => integer() | nil,
    :"user_alias_created" => LabelUser | nil,
    :"responses" => [DraftPaymentResponse] | nil,
    :"status" => String.t | nil,
    :"type" => String.t | nil,
    :"entries" => [DraftPaymentEntry] | nil,
    :"object" => DraftPaymentAnchorObject | nil,
    :"request_reference_split_the_bill" => [RequestInquiryReference] | nil,
    :"schedule" => Schedule | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.DraftPaymentListing do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"user_alias_created", :struct, Bunq.Model.LabelUser, options)
    |> deserialize(:"responses", :list, Bunq.Model.DraftPaymentResponse, options)
    |> deserialize(:"entries", :list, Bunq.Model.DraftPaymentEntry, options)
    |> deserialize(:"object", :struct, Bunq.Model.DraftPaymentAnchorObject, options)
    |> deserialize(:"request_reference_split_the_bill", :list, Bunq.Model.RequestInquiryReference, options)
    |> deserialize(:"schedule", :struct, Bunq.Model.Schedule, options)
  end
end

