# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.DraftPaymentEntry do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"amount",
    :"counterparty_alias",
    :"description",
    :"merchant_reference",
    :"attachment",
    :"id",
    :"alias",
    :"type"
  ]

  @type t :: %__MODULE__{
    :"amount" => Amount | nil,
    :"counterparty_alias" => LabelMonetaryAccount | nil,
    :"description" => String.t | nil,
    :"merchant_reference" => String.t | nil,
    :"attachment" => [AttachmentMonetaryAccountPayment] | nil,
    :"id" => integer() | nil,
    :"alias" => LabelMonetaryAccount | nil,
    :"type" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.DraftPaymentEntry do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"amount", :struct, Bunq.Model.Amount, options)
    |> deserialize(:"counterparty_alias", :struct, Bunq.Model.LabelMonetaryAccount, options)
    |> deserialize(:"attachment", :list, Bunq.Model.AttachmentMonetaryAccountPayment, options)
    |> deserialize(:"alias", :struct, Bunq.Model.LabelMonetaryAccount, options)
  end
end

