# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.DraftPayment do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"status",
    :"entries",
    :"previous_updated_timestamp",
    :"number_of_required_accepts",
    :"schedule"
  ]

  @type t :: %__MODULE__{
    :"status" => String.t | nil,
    :"entries" => [DraftPaymentEntry],
    :"previous_updated_timestamp" => String.t | nil,
    :"number_of_required_accepts" => integer(),
    :"schedule" => Schedule | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.DraftPayment do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"entries", :list, Bunq.Model.DraftPaymentEntry, options)
    |> deserialize(:"schedule", :struct, Bunq.Model.Schedule, options)
  end
end

