# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.EventRead do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"created",
    :"updated",
    :"action",
    :"user_id",
    :"monetary_account_id",
    :"object",
    :"status"
  ]

  @type t :: %__MODULE__{
    :"id" => integer() | nil,
    :"created" => String.t | nil,
    :"updated" => String.t | nil,
    :"action" => String.t | nil,
    :"user_id" => String.t | nil,
    :"monetary_account_id" => String.t | nil,
    :"object" => EventObject | nil,
    :"status" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.EventRead do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"object", :struct, Bunq.Model.EventObject, options)
  end
end

