# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.FeatureAnnouncement do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"avatar",
    :"title",
    :"sub_title"
  ]

  @type t :: %__MODULE__{
    :"avatar" => Avatar | nil,
    :"title" => String.t | nil,
    :"sub_title" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.FeatureAnnouncement do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"avatar", :struct, Bunq.Model.Avatar, options)
  end
end

