# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.Image do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"attachment_public_uuid",
    :"content_type",
    :"height",
    :"width"
  ]

  @type t :: %__MODULE__{
    :"attachment_public_uuid" => String.t | nil,
    :"content_type" => String.t | nil,
    :"height" => integer() | nil,
    :"width" => integer() | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.Image do
  def decode(value, _options) do
    value
  end
end

