# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.InlineResponse400 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Error"
  ]

  @type t :: %__MODULE__{
    :"Error" => [Map] | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.InlineResponse400 do
  def decode(value, _options) do
    value
  end
end

