# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.Installation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"client_public_key"
  ]

  @type t :: %__MODULE__{
    :"client_public_key" => String.t
  }
end

defimpl Poison.Decoder, for: Bunq.Model.Installation do
  def decode(value, _options) do
    value
  end
end

