# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.InvoiceItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"billing_date",
    :"type_description",
    :"type_description_translated",
    :"unit_vat_exclusive",
    :"unit_vat_inclusive",
    :"vat",
    :"quantity",
    :"total_vat_exclusive",
    :"total_vat_inclusive"
  ]

  @type t :: %__MODULE__{
    :"billing_date" => String.t | nil,
    :"type_description" => String.t | nil,
    :"type_description_translated" => String.t | nil,
    :"unit_vat_exclusive" => Amount | nil,
    :"unit_vat_inclusive" => Amount | nil,
    :"vat" => integer() | nil,
    :"quantity" => integer() | nil,
    :"total_vat_exclusive" => Amount | nil,
    :"total_vat_inclusive" => Amount | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.InvoiceItem do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"unit_vat_exclusive", :struct, Bunq.Model.Amount, options)
    |> deserialize(:"unit_vat_inclusive", :struct, Bunq.Model.Amount, options)
    |> deserialize(:"total_vat_exclusive", :struct, Bunq.Model.Amount, options)
    |> deserialize(:"total_vat_inclusive", :struct, Bunq.Model.Amount, options)
  end
end

