# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.InvoiceItemGroup do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"type",
    :"type_description",
    :"type_description_translated",
    :"instance_description",
    :"product_vat_exclusive",
    :"product_vat_inclusive",
    :"item"
  ]

  @type t :: %__MODULE__{
    :"type" => String.t | nil,
    :"type_description" => String.t | nil,
    :"type_description_translated" => String.t | nil,
    :"instance_description" => String.t | nil,
    :"product_vat_exclusive" => Amount | nil,
    :"product_vat_inclusive" => Amount | nil,
    :"item" => InvoiceItem | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.InvoiceItemGroup do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"product_vat_exclusive", :struct, Bunq.Model.Amount, options)
    |> deserialize(:"product_vat_inclusive", :struct, Bunq.Model.Amount, options)
    |> deserialize(:"item", :struct, Bunq.Model.InvoiceItem, options)
  end
end

