# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.LabelUser do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"uuid",
    :"display_name",
    :"country",
    :"avatar",
    :"public_nick_name"
  ]

  @type t :: %__MODULE__{
    :"uuid" => String.t | nil,
    :"display_name" => String.t | nil,
    :"country" => String.t | nil,
    :"avatar" => Avatar | nil,
    :"public_nick_name" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.LabelUser do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"avatar", :struct, Bunq.Model.Avatar, options)
  end
end

