# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.LabelCard do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"uuid",
    :"type",
    :"second_line",
    :"expiry_date",
    :"status",
    :"label_user"
  ]

  @type t :: %__MODULE__{
    :"uuid" => String.t | nil,
    :"type" => String.t | nil,
    :"second_line" => String.t | nil,
    :"expiry_date" => String.t | nil,
    :"status" => String.t | nil,
    :"label_user" => LabelUser | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.LabelCard do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"label_user", :struct, Bunq.Model.LabelUser, options)
  end
end

