# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.LabelMonetaryAccount do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"iban",
    :"display_name",
    :"avatar",
    :"label_user",
    :"country",
    :"bunq_me",
    :"is_light",
    :"swift_bic",
    :"swift_account_number",
    :"transferwise_account_number",
    :"transferwise_bank_code"
  ]

  @type t :: %__MODULE__{
    :"iban" => String.t | nil,
    :"display_name" => String.t | nil,
    :"avatar" => Avatar | nil,
    :"label_user" => LabelUser | nil,
    :"country" => String.t | nil,
    :"bunq_me" => Pointer | nil,
    :"is_light" => boolean() | nil,
    :"swift_bic" => String.t | nil,
    :"swift_account_number" => String.t | nil,
    :"transferwise_account_number" => String.t | nil,
    :"transferwise_bank_code" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.LabelMonetaryAccount do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"avatar", :struct, Bunq.Model.Avatar, options)
    |> deserialize(:"label_user", :struct, Bunq.Model.LabelUser, options)
    |> deserialize(:"bunq_me", :struct, Bunq.Model.Pointer, options)
  end
end

