# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.MonetaryAccountProfileDrain do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"status",
    :"balance_preferred",
    :"balance_threshold_high",
    :"savings_account_alias"
  ]

  @type t :: %__MODULE__{
    :"status" => String.t | nil,
    :"balance_preferred" => Amount | nil,
    :"balance_threshold_high" => Amount | nil,
    :"savings_account_alias" => LabelMonetaryAccount | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.MonetaryAccountProfileDrain do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"balance_preferred", :struct, Bunq.Model.Amount, options)
    |> deserialize(:"balance_threshold_high", :struct, Bunq.Model.Amount, options)
    |> deserialize(:"savings_account_alias", :struct, Bunq.Model.LabelMonetaryAccount, options)
  end
end

