# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.MonetaryAccountJoint do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"currency",
    :"description",
    :"daily_limit",
    :"overdraft_limit",
    :"alias",
    :"avatar_uuid",
    :"status",
    :"sub_status",
    :"reason",
    :"reason_description",
    :"all_co_owner",
    :"notification_filters",
    :"setting"
  ]

  @type t :: %__MODULE__{
    :"currency" => String.t,
    :"description" => String.t | nil,
    :"daily_limit" => Amount | nil,
    :"overdraft_limit" => Amount | nil,
    :"alias" => [Pointer] | nil,
    :"avatar_uuid" => String.t | nil,
    :"status" => String.t | nil,
    :"sub_status" => String.t | nil,
    :"reason" => String.t | nil,
    :"reason_description" => String.t | nil,
    :"all_co_owner" => [CoOwner],
    :"notification_filters" => [NotificationFilter] | nil,
    :"setting" => MonetaryAccountSetting | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.MonetaryAccountJoint do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"daily_limit", :struct, Bunq.Model.Amount, options)
    |> deserialize(:"overdraft_limit", :struct, Bunq.Model.Amount, options)
    |> deserialize(:"alias", :list, Bunq.Model.Pointer, options)
    |> deserialize(:"all_co_owner", :list, Bunq.Model.CoOwner, options)
    |> deserialize(:"notification_filters", :list, Bunq.Model.NotificationFilter, options)
    |> deserialize(:"setting", :struct, Bunq.Model.MonetaryAccountSetting, options)
  end
end

