# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.MonetaryAccountListing do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"MonetaryAccountBank",
    :"MonetaryAccountJoint",
    :"MonetaryAccountLight",
    :"MonetaryAccountSavings"
  ]

  @type t :: %__MODULE__{
    :"MonetaryAccountBank" => MonetaryAccountBank | nil,
    :"MonetaryAccountJoint" => MonetaryAccountJoint | nil,
    :"MonetaryAccountLight" => MonetaryAccountLight | nil,
    :"MonetaryAccountSavings" => MonetaryAccountSavings | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.MonetaryAccountListing do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"MonetaryAccountBank", :struct, Bunq.Model.MonetaryAccountBank, options)
    |> deserialize(:"MonetaryAccountJoint", :struct, Bunq.Model.MonetaryAccountJoint, options)
    |> deserialize(:"MonetaryAccountLight", :struct, Bunq.Model.MonetaryAccountLight, options)
    |> deserialize(:"MonetaryAccountSavings", :struct, Bunq.Model.MonetaryAccountSavings, options)
  end
end

