# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.MonetaryAccountSavingsRead do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"created",
    :"updated",
    :"avatar",
    :"currency",
    :"description",
    :"daily_limit",
    :"daily_spent",
    :"overdraft_limit",
    :"balance",
    :"alias",
    :"public_uuid",
    :"status",
    :"sub_status",
    :"reason",
    :"reason_description",
    :"all_co_owner",
    :"user_id",
    :"monetary_account_profile",
    :"notification_filters",
    :"setting",
    :"savings_goal",
    :"savings_goal_progress"
  ]

  @type t :: %__MODULE__{
    :"id" => integer() | nil,
    :"created" => String.t | nil,
    :"updated" => String.t | nil,
    :"avatar" => Avatar | nil,
    :"currency" => String.t | nil,
    :"description" => String.t | nil,
    :"daily_limit" => Amount | nil,
    :"daily_spent" => Amount | nil,
    :"overdraft_limit" => Amount | nil,
    :"balance" => Amount | nil,
    :"alias" => [Pointer] | nil,
    :"public_uuid" => String.t | nil,
    :"status" => String.t | nil,
    :"sub_status" => String.t | nil,
    :"reason" => String.t | nil,
    :"reason_description" => String.t | nil,
    :"all_co_owner" => [CoOwner] | nil,
    :"user_id" => integer() | nil,
    :"monetary_account_profile" => MonetaryAccountProfile | nil,
    :"notification_filters" => [NotificationFilter] | nil,
    :"setting" => MonetaryAccountSetting | nil,
    :"savings_goal" => Amount | nil,
    :"savings_goal_progress" => integer() | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.MonetaryAccountSavingsRead do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"avatar", :struct, Bunq.Model.Avatar, options)
    |> deserialize(:"daily_limit", :struct, Bunq.Model.Amount, options)
    |> deserialize(:"daily_spent", :struct, Bunq.Model.Amount, options)
    |> deserialize(:"overdraft_limit", :struct, Bunq.Model.Amount, options)
    |> deserialize(:"balance", :struct, Bunq.Model.Amount, options)
    |> deserialize(:"alias", :list, Bunq.Model.Pointer, options)
    |> deserialize(:"all_co_owner", :list, Bunq.Model.CoOwner, options)
    |> deserialize(:"monetary_account_profile", :struct, Bunq.Model.MonetaryAccountProfile, options)
    |> deserialize(:"notification_filters", :list, Bunq.Model.NotificationFilter, options)
    |> deserialize(:"setting", :struct, Bunq.Model.MonetaryAccountSetting, options)
    |> deserialize(:"savings_goal", :struct, Bunq.Model.Amount, options)
  end
end

