# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.MonetaryAccountSetting do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"color",
    :"icon",
    :"default_avatar_status",
    :"restriction_chat"
  ]

  @type t :: %__MODULE__{
    :"color" => String.t | nil,
    :"icon" => String.t | nil,
    :"default_avatar_status" => String.t | nil,
    :"restriction_chat" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.MonetaryAccountSetting do
  def decode(value, _options) do
    value
  end
end

