# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.MonetaryAccountSavings do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"currency",
    :"description",
    :"daily_limit",
    :"avatar_uuid",
    :"status",
    :"sub_status",
    :"reason",
    :"reason_description",
    :"all_co_owner",
    :"notification_filters",
    :"setting",
    :"savings_goal"
  ]

  @type t :: %__MODULE__{
    :"currency" => String.t,
    :"description" => String.t | nil,
    :"daily_limit" => Amount | nil,
    :"avatar_uuid" => String.t | nil,
    :"status" => String.t | nil,
    :"sub_status" => String.t | nil,
    :"reason" => String.t | nil,
    :"reason_description" => String.t | nil,
    :"all_co_owner" => [CoOwner] | nil,
    :"notification_filters" => [NotificationFilter] | nil,
    :"setting" => MonetaryAccountSetting | nil,
    :"savings_goal" => Amount
  }
end

defimpl Poison.Decoder, for: Bunq.Model.MonetaryAccountSavings do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"daily_limit", :struct, Bunq.Model.Amount, options)
    |> deserialize(:"all_co_owner", :list, Bunq.Model.CoOwner, options)
    |> deserialize(:"notification_filters", :list, Bunq.Model.NotificationFilter, options)
    |> deserialize(:"setting", :struct, Bunq.Model.MonetaryAccountSetting, options)
    |> deserialize(:"savings_goal", :struct, Bunq.Model.Amount, options)
  end
end

