# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.MonetaryAccountProfileFill do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"status",
    :"balance_preferred",
    :"balance_threshold_low",
    :"method_fill",
    :"issuer"
  ]

  @type t :: %__MODULE__{
    :"status" => String.t | nil,
    :"balance_preferred" => Amount | nil,
    :"balance_threshold_low" => Amount | nil,
    :"method_fill" => String.t | nil,
    :"issuer" => Issuer | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.MonetaryAccountProfileFill do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"balance_preferred", :struct, Bunq.Model.Amount, options)
    |> deserialize(:"balance_threshold_low", :struct, Bunq.Model.Amount, options)
    |> deserialize(:"issuer", :struct, Bunq.Model.Issuer, options)
  end
end

