# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.NoteAttachmentPaymentBatch do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"description",
    :"attachment_id"
  ]

  @type t :: %__MODULE__{
    :"description" => String.t | nil,
    :"attachment_id" => integer()
  }
end

defimpl Poison.Decoder, for: Bunq.Model.NoteAttachmentPaymentBatch do
  def decode(value, _options) do
    value
  end
end

