# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.NotificationFilterUrlUserListing do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"notification_filters"
  ]

  @type t :: %__MODULE__{
    :"notification_filters" => [NotificationFilterUrl] | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.NotificationFilterUrlUserListing do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"notification_filters", :list, Bunq.Model.NotificationFilterUrl, options)
  end
end

