# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.OauthClientListing do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"status",
    :"client_id",
    :"secret",
    :"callback_url"
  ]

  @type t :: %__MODULE__{
    :"id" => integer() | nil,
    :"status" => String.t | nil,
    :"client_id" => String.t | nil,
    :"secret" => String.t | nil,
    :"callback_url" => [OauthCallbackUrl] | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.OauthClientListing do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"callback_url", :list, Bunq.Model.OauthCallbackUrl, options)
  end
end

