# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.PaymentBatchRead do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"payments"
  ]

  @type t :: %__MODULE__{
    :"payments" => [Payment] | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.PaymentBatchRead do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"payments", :list, Bunq.Model.Payment, options)
  end
end

