# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.PaymentServiceProviderCredential do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"client_payment_service_provider_certificate",
    :"client_payment_service_provider_certificate_chain",
    :"client_public_key_signature"
  ]

  @type t :: %__MODULE__{
    :"client_payment_service_provider_certificate" => String.t,
    :"client_payment_service_provider_certificate_chain" => String.t,
    :"client_public_key_signature" => String.t
  }
end

defimpl Poison.Decoder, for: Bunq.Model.PaymentServiceProviderCredential do
  def decode(value, _options) do
    value
  end
end

