# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.PaymentRead do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"created",
    :"updated",
    :"monetary_account_id",
    :"amount",
    :"alias",
    :"counterparty_alias",
    :"description",
    :"type",
    :"sub_type",
    :"bunqto_status",
    :"bunqto_sub_status",
    :"bunqto_share_url",
    :"bunqto_expiry",
    :"bunqto_time_responded",
    :"attachment",
    :"merchant_reference",
    :"batch_id",
    :"scheduled_id",
    :"address_shipping",
    :"address_billing",
    :"geolocation",
    :"allow_chat",
    :"request_reference_split_the_bill",
    :"balance_after_mutation"
  ]

  @type t :: %__MODULE__{
    :"id" => integer() | nil,
    :"created" => String.t | nil,
    :"updated" => String.t | nil,
    :"monetary_account_id" => integer() | nil,
    :"amount" => Amount | nil,
    :"alias" => LabelMonetaryAccount | nil,
    :"counterparty_alias" => LabelMonetaryAccount | nil,
    :"description" => String.t | nil,
    :"type" => String.t | nil,
    :"sub_type" => String.t | nil,
    :"bunqto_status" => String.t | nil,
    :"bunqto_sub_status" => String.t | nil,
    :"bunqto_share_url" => String.t | nil,
    :"bunqto_expiry" => String.t | nil,
    :"bunqto_time_responded" => String.t | nil,
    :"attachment" => [AttachmentMonetaryAccountPayment] | nil,
    :"merchant_reference" => String.t | nil,
    :"batch_id" => integer() | nil,
    :"scheduled_id" => integer() | nil,
    :"address_shipping" => Address | nil,
    :"address_billing" => Address | nil,
    :"geolocation" => Geolocation | nil,
    :"allow_chat" => boolean() | nil,
    :"request_reference_split_the_bill" => [RequestInquiryReference] | nil,
    :"balance_after_mutation" => Amount | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.PaymentRead do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"amount", :struct, Bunq.Model.Amount, options)
    |> deserialize(:"alias", :struct, Bunq.Model.LabelMonetaryAccount, options)
    |> deserialize(:"counterparty_alias", :struct, Bunq.Model.LabelMonetaryAccount, options)
    |> deserialize(:"attachment", :list, Bunq.Model.AttachmentMonetaryAccountPayment, options)
    |> deserialize(:"address_shipping", :struct, Bunq.Model.Address, options)
    |> deserialize(:"address_billing", :struct, Bunq.Model.Address, options)
    |> deserialize(:"geolocation", :struct, Bunq.Model.Geolocation, options)
    |> deserialize(:"request_reference_split_the_bill", :list, Bunq.Model.RequestInquiryReference, options)
    |> deserialize(:"balance_after_mutation", :struct, Bunq.Model.Amount, options)
  end
end

