# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.RequestReferenceSplitTheBillAnchorObject do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"BillingInvoice",
    :"DraftPayment",
    :"MasterCardAction",
    :"Payment",
    :"PaymentBatch",
    :"RequestResponse",
    :"ScheduleInstance",
    :"TabResultResponse",
    :"WhitelistResult"
  ]

  @type t :: %__MODULE__{
    :"BillingInvoice" => Invoice | nil,
    :"DraftPayment" => DraftPayment | nil,
    :"MasterCardAction" => MasterCardAction | nil,
    :"Payment" => Payment | nil,
    :"PaymentBatch" => PaymentBatch | nil,
    :"RequestResponse" => RequestResponse | nil,
    :"ScheduleInstance" => ScheduleInstance | nil,
    :"TabResultResponse" => TabResultResponse | nil,
    :"WhitelistResult" => WhitelistResult | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.RequestReferenceSplitTheBillAnchorObject do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"BillingInvoice", :struct, Bunq.Model.Invoice, options)
    |> deserialize(:"DraftPayment", :struct, Bunq.Model.DraftPayment, options)
    |> deserialize(:"MasterCardAction", :struct, Bunq.Model.MasterCardAction, options)
    |> deserialize(:"Payment", :struct, Bunq.Model.Payment, options)
    |> deserialize(:"PaymentBatch", :struct, Bunq.Model.PaymentBatch, options)
    |> deserialize(:"RequestResponse", :struct, Bunq.Model.RequestResponse, options)
    |> deserialize(:"ScheduleInstance", :struct, Bunq.Model.ScheduleInstance, options)
    |> deserialize(:"TabResultResponse", :struct, Bunq.Model.TabResultResponse, options)
    |> deserialize(:"WhitelistResult", :struct, Bunq.Model.WhitelistResult, options)
  end
end

