# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.RequestInquiry do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"amount_inquired",
    :"counterparty_alias",
    :"description",
    :"attachment",
    :"merchant_reference",
    :"status",
    :"minimum_age",
    :"require_address",
    :"want_tip",
    :"allow_amount_lower",
    :"allow_amount_higher",
    :"allow_bunqme",
    :"redirect_url",
    :"event_id",
    :"id",
    :"created",
    :"updated",
    :"time_responded",
    :"time_expiry",
    :"monetary_account_id",
    :"amount_responded",
    :"user_alias_created",
    :"user_alias_revoked",
    :"batch_id",
    :"scheduled_id",
    :"bunqme_share_url",
    :"address_shipping",
    :"address_billing",
    :"geolocation",
    :"allow_chat",
    :"reference_split_the_bill"
  ]

  @type t :: %__MODULE__{
    :"amount_inquired" => Amount | nil,
    :"counterparty_alias" => LabelMonetaryAccount | nil,
    :"description" => String.t | nil,
    :"attachment" => [BunqId] | nil,
    :"merchant_reference" => String.t | nil,
    :"status" => String.t | nil,
    :"minimum_age" => integer() | nil,
    :"require_address" => String.t | nil,
    :"want_tip" => boolean() | nil,
    :"allow_amount_lower" => boolean() | nil,
    :"allow_amount_higher" => boolean() | nil,
    :"allow_bunqme" => boolean(),
    :"redirect_url" => String.t | nil,
    :"event_id" => integer() | nil,
    :"id" => integer() | nil,
    :"created" => String.t | nil,
    :"updated" => String.t | nil,
    :"time_responded" => String.t | nil,
    :"time_expiry" => String.t | nil,
    :"monetary_account_id" => integer() | nil,
    :"amount_responded" => Amount | nil,
    :"user_alias_created" => LabelUser | nil,
    :"user_alias_revoked" => LabelUser | nil,
    :"batch_id" => integer() | nil,
    :"scheduled_id" => integer() | nil,
    :"bunqme_share_url" => String.t | nil,
    :"address_shipping" => Address | nil,
    :"address_billing" => Address | nil,
    :"geolocation" => Geolocation | nil,
    :"allow_chat" => boolean() | nil,
    :"reference_split_the_bill" => RequestReferenceSplitTheBillAnchorObject | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.RequestInquiry do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"amount_inquired", :struct, Bunq.Model.Amount, options)
    |> deserialize(:"counterparty_alias", :struct, Bunq.Model.LabelMonetaryAccount, options)
    |> deserialize(:"attachment", :list, Bunq.Model.BunqId, options)
    |> deserialize(:"amount_responded", :struct, Bunq.Model.Amount, options)
    |> deserialize(:"user_alias_created", :struct, Bunq.Model.LabelUser, options)
    |> deserialize(:"user_alias_revoked", :struct, Bunq.Model.LabelUser, options)
    |> deserialize(:"address_shipping", :struct, Bunq.Model.Address, options)
    |> deserialize(:"address_billing", :struct, Bunq.Model.Address, options)
    |> deserialize(:"geolocation", :struct, Bunq.Model.Geolocation, options)
    |> deserialize(:"reference_split_the_bill", :struct, Bunq.Model.RequestReferenceSplitTheBillAnchorObject, options)
  end
end

