# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.RequestInquiryUpdate do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"created",
    :"updated",
    :"time_responded",
    :"time_expiry",
    :"monetary_account_id",
    :"amount_inquired",
    :"amount_responded",
    :"user_alias_created",
    :"user_alias_revoked",
    :"counterparty_alias",
    :"description",
    :"merchant_reference",
    :"attachment",
    :"status",
    :"batch_id",
    :"scheduled_id",
    :"minimum_age",
    :"require_address",
    :"address_shipping",
    :"address_billing",
    :"geolocation",
    :"reference_split_the_bill"
  ]

  @type t :: %__MODULE__{
    :"id" => integer() | nil,
    :"created" => String.t | nil,
    :"updated" => String.t | nil,
    :"time_responded" => String.t | nil,
    :"time_expiry" => String.t | nil,
    :"monetary_account_id" => integer() | nil,
    :"amount_inquired" => Amount | nil,
    :"amount_responded" => Amount | nil,
    :"user_alias_created" => LabelUser | nil,
    :"user_alias_revoked" => LabelUser | nil,
    :"counterparty_alias" => LabelMonetaryAccount | nil,
    :"description" => String.t | nil,
    :"merchant_reference" => String.t | nil,
    :"attachment" => [BunqId] | nil,
    :"status" => String.t | nil,
    :"batch_id" => integer() | nil,
    :"scheduled_id" => integer() | nil,
    :"minimum_age" => integer() | nil,
    :"require_address" => String.t | nil,
    :"address_shipping" => Address | nil,
    :"address_billing" => Address | nil,
    :"geolocation" => Geolocation | nil,
    :"reference_split_the_bill" => RequestReferenceSplitTheBillAnchorObject | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.RequestInquiryUpdate do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"amount_inquired", :struct, Bunq.Model.Amount, options)
    |> deserialize(:"amount_responded", :struct, Bunq.Model.Amount, options)
    |> deserialize(:"user_alias_created", :struct, Bunq.Model.LabelUser, options)
    |> deserialize(:"user_alias_revoked", :struct, Bunq.Model.LabelUser, options)
    |> deserialize(:"counterparty_alias", :struct, Bunq.Model.LabelMonetaryAccount, options)
    |> deserialize(:"attachment", :list, Bunq.Model.BunqId, options)
    |> deserialize(:"address_shipping", :struct, Bunq.Model.Address, options)
    |> deserialize(:"address_billing", :struct, Bunq.Model.Address, options)
    |> deserialize(:"geolocation", :struct, Bunq.Model.Geolocation, options)
    |> deserialize(:"reference_split_the_bill", :struct, Bunq.Model.RequestReferenceSplitTheBillAnchorObject, options)
  end
end

