# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.RewardSenderListing do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"created",
    :"updated",
    :"status",
    :"sub_status",
    :"type",
    :"counterparty_alias",
    :"amount_reward"
  ]

  @type t :: %__MODULE__{
    :"id" => integer() | nil,
    :"created" => String.t | nil,
    :"updated" => String.t | nil,
    :"status" => String.t | nil,
    :"sub_status" => String.t | nil,
    :"type" => String.t | nil,
    :"counterparty_alias" => LabelUser | nil,
    :"amount_reward" => Amount | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.RewardSenderListing do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"counterparty_alias", :struct, Bunq.Model.LabelUser, options)
    |> deserialize(:"amount_reward", :struct, Bunq.Model.Amount, options)
  end
end

