# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.SchedulePaymentEntry do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"amount",
    :"counterparty_alias",
    :"description",
    :"attachment",
    :"merchant_reference",
    :"allow_bunqto",
    :"alias"
  ]

  @type t :: %__MODULE__{
    :"amount" => Amount | nil,
    :"counterparty_alias" => LabelMonetaryAccount | nil,
    :"description" => String.t | nil,
    :"attachment" => [AttachmentMonetaryAccountPayment] | nil,
    :"merchant_reference" => String.t | nil,
    :"allow_bunqto" => boolean() | nil,
    :"alias" => LabelMonetaryAccount | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.SchedulePaymentEntry do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"amount", :struct, Bunq.Model.Amount, options)
    |> deserialize(:"counterparty_alias", :struct, Bunq.Model.LabelMonetaryAccount, options)
    |> deserialize(:"attachment", :list, Bunq.Model.AttachmentMonetaryAccountPayment, options)
    |> deserialize(:"alias", :struct, Bunq.Model.LabelMonetaryAccount, options)
  end
end

