# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.SessionServerCreate do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Id",
    :"Token",
    :"UserCompany",
    :"UserPerson",
    :"UserApiKey",
    :"UserPaymentServiceProvider"
  ]

  @type t :: %__MODULE__{
    :"Id" => BunqId | nil,
    :"Token" => SessionServerToken | nil,
    :"UserCompany" => UserCompany | nil,
    :"UserPerson" => UserPerson | nil,
    :"UserApiKey" => UserApiKey | nil,
    :"UserPaymentServiceProvider" => UserPaymentServiceProvider | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.SessionServerCreate do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Id", :struct, Bunq.Model.BunqId, options)
    |> deserialize(:"Token", :struct, Bunq.Model.SessionServerToken, options)
    |> deserialize(:"UserCompany", :struct, Bunq.Model.UserCompany, options)
    |> deserialize(:"UserPerson", :struct, Bunq.Model.UserPerson, options)
    |> deserialize(:"UserApiKey", :struct, Bunq.Model.UserApiKey, options)
    |> deserialize(:"UserPaymentServiceProvider", :struct, Bunq.Model.UserPaymentServiceProvider, options)
  end
end

