# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.ShareInviteMonetaryAccountResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"status",
    :"card_id"
  ]

  @type t :: %__MODULE__{
    :"status" => String.t | nil,
    :"card_id" => integer() | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.ShareInviteMonetaryAccountResponse do
  def decode(value, _options) do
    value
  end
end

