# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.ShareDetail do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"payment",
    :"read_only",
    :"draft_payment"
  ]

  @type t :: %__MODULE__{
    :"payment" => ShareDetailPayment | nil,
    :"read_only" => ShareDetailReadOnly | nil,
    :"draft_payment" => ShareDetailDraftPayment | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.ShareDetail do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"payment", :struct, Bunq.Model.ShareDetailPayment, options)
    |> deserialize(:"read_only", :struct, Bunq.Model.ShareDetailReadOnly, options)
    |> deserialize(:"draft_payment", :struct, Bunq.Model.ShareDetailDraftPayment, options)
  end
end

