# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.ShareInviteBankInquiryBatch do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"share_invite_bank_inquiries",
    :"alias"
  ]

  @type t :: %__MODULE__{
    :"share_invite_bank_inquiries" => [ShareInviteBankInquiry] | nil,
    :"alias" => LabelMonetaryAccount | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.ShareInviteBankInquiryBatch do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"share_invite_bank_inquiries", :list, Bunq.Model.ShareInviteBankInquiry, options)
    |> deserialize(:"alias", :struct, Bunq.Model.LabelMonetaryAccount, options)
  end
end

