# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.ShareInviteMonetaryAccountInquiryRead do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"alias",
    :"user_alias_created",
    :"user_alias_revoked",
    :"counter_user_alias",
    :"monetary_account_id",
    :"draft_share_invite_bank_id",
    :"share_detail",
    :"status",
    :"share_type",
    :"start_date",
    :"end_date",
    :"id"
  ]

  @type t :: %__MODULE__{
    :"alias" => LabelMonetaryAccount | nil,
    :"user_alias_created" => LabelUser | nil,
    :"user_alias_revoked" => LabelUser | nil,
    :"counter_user_alias" => LabelUser | nil,
    :"monetary_account_id" => integer() | nil,
    :"draft_share_invite_bank_id" => integer() | nil,
    :"share_detail" => ShareDetail | nil,
    :"status" => String.t | nil,
    :"share_type" => String.t | nil,
    :"start_date" => String.t | nil,
    :"end_date" => String.t | nil,
    :"id" => integer() | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.ShareInviteMonetaryAccountInquiryRead do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"alias", :struct, Bunq.Model.LabelMonetaryAccount, options)
    |> deserialize(:"user_alias_created", :struct, Bunq.Model.LabelUser, options)
    |> deserialize(:"user_alias_revoked", :struct, Bunq.Model.LabelUser, options)
    |> deserialize(:"counter_user_alias", :struct, Bunq.Model.LabelUser, options)
    |> deserialize(:"share_detail", :struct, Bunq.Model.ShareDetail, options)
  end
end

