# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.ShareDetailReadOnly do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"view_balance",
    :"view_old_events",
    :"view_new_events"
  ]

  @type t :: %__MODULE__{
    :"view_balance" => boolean() | nil,
    :"view_old_events" => boolean() | nil,
    :"view_new_events" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.ShareDetailReadOnly do
  def decode(value, _options) do
    value
  end
end

