# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.ShareDetailPayment do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"make_payments",
    :"make_draft_payments",
    :"view_balance",
    :"view_old_events",
    :"view_new_events",
    :"budget"
  ]

  @type t :: %__MODULE__{
    :"make_payments" => boolean() | nil,
    :"make_draft_payments" => boolean() | nil,
    :"view_balance" => boolean() | nil,
    :"view_old_events" => boolean() | nil,
    :"view_new_events" => boolean() | nil,
    :"budget" => BudgetRestriction | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.ShareDetailPayment do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"budget", :struct, Bunq.Model.BudgetRestriction, options)
  end
end

