# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.ShareInviteMonetaryAccountResponseListing do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"created",
    :"updated",
    :"counter_alias",
    :"user_alias_cancelled",
    :"monetary_account_id",
    :"draft_share_invite_bank_id",
    :"share_detail",
    :"status",
    :"share_type",
    :"start_date",
    :"end_date",
    :"description"
  ]

  @type t :: %__MODULE__{
    :"id" => integer() | nil,
    :"created" => String.t | nil,
    :"updated" => String.t | nil,
    :"counter_alias" => LabelMonetaryAccount | nil,
    :"user_alias_cancelled" => LabelUser | nil,
    :"monetary_account_id" => integer() | nil,
    :"draft_share_invite_bank_id" => integer() | nil,
    :"share_detail" => ShareDetail | nil,
    :"status" => String.t | nil,
    :"share_type" => String.t | nil,
    :"start_date" => String.t | nil,
    :"end_date" => String.t | nil,
    :"description" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.ShareInviteMonetaryAccountResponseListing do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"counter_alias", :struct, Bunq.Model.LabelMonetaryAccount, options)
    |> deserialize(:"user_alias_cancelled", :struct, Bunq.Model.LabelUser, options)
    |> deserialize(:"share_detail", :struct, Bunq.Model.ShareDetail, options)
  end
end

