# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.Tab do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"TabUsageSingle",
    :"TabUsageMultiple"
  ]

  @type t :: %__MODULE__{
    :"TabUsageSingle" => TabUsageSingle | nil,
    :"TabUsageMultiple" => TabUsageMultiple | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.Tab do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"TabUsageSingle", :struct, Bunq.Model.TabUsageSingle, options)
    |> deserialize(:"TabUsageMultiple", :struct, Bunq.Model.TabUsageMultiple, options)
  end
end

