# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.TabItemShopBatch do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"tab_items"
  ]

  @type t :: %__MODULE__{
    :"tab_items" => [TabItemShop]
  }
end

defimpl Poison.Decoder, for: Bunq.Model.TabItemShopBatch do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"tab_items", :list, Bunq.Model.TabItemShop, options)
  end
end

