# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.TokenQrRequestIdealCreate do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"time_responded",
    :"time_expiry",
    :"monetary_account_id",
    :"amount_inquired",
    :"amount_responded",
    :"alias",
    :"counterparty_alias",
    :"description",
    :"attachment",
    :"status",
    :"minimum_age",
    :"require_address",
    :"address_shipping",
    :"address_billing",
    :"geolocation",
    :"redirect_url",
    :"type",
    :"sub_type",
    :"allow_chat",
    :"eligible_whitelist_id"
  ]

  @type t :: %__MODULE__{
    :"id" => integer() | nil,
    :"time_responded" => String.t | nil,
    :"time_expiry" => String.t | nil,
    :"monetary_account_id" => integer() | nil,
    :"amount_inquired" => Amount | nil,
    :"amount_responded" => Amount | nil,
    :"alias" => LabelMonetaryAccount | nil,
    :"counterparty_alias" => LabelMonetaryAccount | nil,
    :"description" => String.t | nil,
    :"attachment" => [Attachment] | nil,
    :"status" => String.t | nil,
    :"minimum_age" => integer() | nil,
    :"require_address" => String.t | nil,
    :"address_shipping" => Address | nil,
    :"address_billing" => Address | nil,
    :"geolocation" => Geolocation | nil,
    :"redirect_url" => String.t | nil,
    :"type" => String.t | nil,
    :"sub_type" => String.t | nil,
    :"allow_chat" => boolean() | nil,
    :"eligible_whitelist_id" => integer() | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.TokenQrRequestIdealCreate do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"amount_inquired", :struct, Bunq.Model.Amount, options)
    |> deserialize(:"amount_responded", :struct, Bunq.Model.Amount, options)
    |> deserialize(:"alias", :struct, Bunq.Model.LabelMonetaryAccount, options)
    |> deserialize(:"counterparty_alias", :struct, Bunq.Model.LabelMonetaryAccount, options)
    |> deserialize(:"attachment", :list, Bunq.Model.Attachment, options)
    |> deserialize(:"address_shipping", :struct, Bunq.Model.Address, options)
    |> deserialize(:"address_billing", :struct, Bunq.Model.Address, options)
    |> deserialize(:"geolocation", :struct, Bunq.Model.Geolocation, options)
  end
end

