# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.UserApiKey do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"created",
    :"updated",
    :"requested_by_user",
    :"granted_by_user"
  ]

  @type t :: %__MODULE__{
    :"id" => integer() | nil,
    :"created" => String.t | nil,
    :"updated" => String.t | nil,
    :"requested_by_user" => UserApiKeyAnchoredUser | nil,
    :"granted_by_user" => UserApiKeyAnchoredUser | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.UserApiKey do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"requested_by_user", :struct, Bunq.Model.UserApiKeyAnchoredUser, options)
    |> deserialize(:"granted_by_user", :struct, Bunq.Model.UserApiKeyAnchoredUser, options)
  end
end

