# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.UserCompanyNameListing do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name_array"
  ]

  @type t :: %__MODULE__{
    :"name_array" => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.UserCompanyNameListing do
  def decode(value, _options) do
    value
  end
end

