# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.UserCredentialPasswordIpRead do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"created",
    :"updated",
    :"status",
    :"expiry_time",
    :"token_value",
    :"permitted_device"
  ]

  @type t :: %__MODULE__{
    :"id" => integer() | nil,
    :"created" => String.t | nil,
    :"updated" => String.t | nil,
    :"status" => String.t | nil,
    :"expiry_time" => String.t | nil,
    :"token_value" => String.t | nil,
    :"permitted_device" => PermittedDevice | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.UserCredentialPasswordIpRead do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"permitted_device", :struct, Bunq.Model.PermittedDevice, options)
  end
end

