# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.UserCompany do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"public_nick_name",
    :"avatar_uuid",
    :"address_main",
    :"address_postal",
    :"language",
    :"region",
    :"country",
    :"ubo",
    :"chamber_of_commerce_number",
    :"legal_form",
    :"status",
    :"sub_status",
    :"session_timeout",
    :"daily_limit_without_confirmation_login",
    :"notification_filters",
    :"id",
    :"created",
    :"updated",
    :"public_uuid",
    :"display_name",
    :"alias",
    :"type_of_business_entity",
    :"sector_of_industry",
    :"counter_bank_iban",
    :"avatar",
    :"version_terms_of_service",
    :"director_alias",
    :"customer",
    :"customer_limit",
    :"billing_contract"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t | nil,
    :"public_nick_name" => String.t | nil,
    :"avatar_uuid" => String.t | nil,
    :"address_main" => Address | nil,
    :"address_postal" => Address | nil,
    :"language" => String.t | nil,
    :"region" => String.t | nil,
    :"country" => String.t | nil,
    :"ubo" => [Ubo] | nil,
    :"chamber_of_commerce_number" => String.t | nil,
    :"legal_form" => String.t | nil,
    :"status" => String.t | nil,
    :"sub_status" => String.t | nil,
    :"session_timeout" => integer() | nil,
    :"daily_limit_without_confirmation_login" => Amount | nil,
    :"notification_filters" => [NotificationFilter] | nil,
    :"id" => integer() | nil,
    :"created" => String.t | nil,
    :"updated" => String.t | nil,
    :"public_uuid" => String.t | nil,
    :"display_name" => String.t | nil,
    :"alias" => [Pointer] | nil,
    :"type_of_business_entity" => String.t | nil,
    :"sector_of_industry" => String.t | nil,
    :"counter_bank_iban" => String.t | nil,
    :"avatar" => Avatar | nil,
    :"version_terms_of_service" => String.t | nil,
    :"director_alias" => LabelUser | nil,
    :"customer" => Customer | nil,
    :"customer_limit" => CustomerLimit | nil,
    :"billing_contract" => [BillingContractSubscription] | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.UserCompany do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"address_main", :struct, Bunq.Model.Address, options)
    |> deserialize(:"address_postal", :struct, Bunq.Model.Address, options)
    |> deserialize(:"ubo", :list, Bunq.Model.Ubo, options)
    |> deserialize(:"daily_limit_without_confirmation_login", :struct, Bunq.Model.Amount, options)
    |> deserialize(:"notification_filters", :list, Bunq.Model.NotificationFilter, options)
    |> deserialize(:"alias", :list, Bunq.Model.Pointer, options)
    |> deserialize(:"avatar", :struct, Bunq.Model.Avatar, options)
    |> deserialize(:"director_alias", :struct, Bunq.Model.LabelUser, options)
    |> deserialize(:"customer", :struct, Bunq.Model.Customer, options)
    |> deserialize(:"customer_limit", :struct, Bunq.Model.CustomerLimit, options)
    |> deserialize(:"billing_contract", :list, Bunq.Model.BillingContractSubscription, options)
  end
end

