# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.WhitelistSdd do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"monetary_account_paying_id",
    :"request_id",
    :"maximum_amount_per_month"
  ]

  @type t :: %__MODULE__{
    :"monetary_account_paying_id" => integer(),
    :"request_id" => integer(),
    :"maximum_amount_per_month" => Amount
  }
end

defimpl Poison.Decoder, for: Bunq.Model.WhitelistSdd do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"maximum_amount_per_month", :struct, Bunq.Model.Amount, options)
  end
end

