# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Bunq.Model.WhitelistSddRead do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"monetary_account_incoming_id",
    :"monetary_account_paying_id",
    :"type",
    :"status",
    :"credit_scheme_identifier",
    :"mandate_identifier",
    :"counterparty_alias",
    :"maximum_amount_per_month",
    :"user_alias_created"
  ]

  @type t :: %__MODULE__{
    :"id" => integer() | nil,
    :"monetary_account_incoming_id" => integer() | nil,
    :"monetary_account_paying_id" => integer() | nil,
    :"type" => String.t | nil,
    :"status" => String.t | nil,
    :"credit_scheme_identifier" => String.t | nil,
    :"mandate_identifier" => String.t | nil,
    :"counterparty_alias" => LabelMonetaryAccount | nil,
    :"maximum_amount_per_month" => Amount | nil,
    :"user_alias_created" => LabelUser | nil
  }
end

defimpl Poison.Decoder, for: Bunq.Model.WhitelistSddRead do
  import Bunq.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"counterparty_alias", :struct, Bunq.Model.LabelMonetaryAccount, options)
    |> deserialize(:"maximum_amount_per_month", :struct, Bunq.Model.Amount, options)
    |> deserialize(:"user_alias_created", :struct, Bunq.Model.LabelUser, options)
  end
end

